### PR TITLE
Add line dash option to Overlay class

### PR DESCRIPTION
**Pull request by pmatsson**
This Pull Request introduces a new feature to the Overlay class - the ability to draw shapes with dashed lines. This enhancement provides additional flexibility in the visual representation of shapes. 

Please review the changes and provide any feedback. Thank you.

image

### CODE REVIEW

**Review by bmatthieu3 — CHANGES_REQUESTED** [review]
This is a great contribution and simple to add too. Thank you. I have a few remarks:
* Could you add a little documentation as well with the possible values of lineDash 
* I would also add a similar options for Catalog since they can have footprints associated.

**Comment by ManonMarchand** [comment]
This feature would be nice for the support of regions visuals in https://github.com/cds-astro/ipyaladin/pull/88
@bmatthieu3 is there something blocking the merge?

**Comment by bmatthieu3** [comment]
@ManonMarchand - Not that much, just some doc API that I will do

**Comment by bmatthieu3** [comment]
@pmatsson - Thanks, I fixed a little thing: when finishing drawing an overlay with a dash line, if there are other things to draw after, it would have drawn them dashed too.

**Pull request merged**
