### PR TITLE
A proposal of a new feature - fill the polygon with a color

### PR DESCRIPTION
**Pull request by szpetny**
I would like to propose a new feature. The possibility to fill the polygon with a given color with given transparency.

This code seems to work ok, but I've noticed some problems for some of the projections, when the polygons are rendered near the edge of the globe (see the first attached picture, it is projection MOL). Don't know what is the problem, but it also occurs for just drawing the polygons (see the second attached picture - for projection HPX)

image

image

### CODE REVIEW

**Comment by bmatthieu3** [comment]
It is a great missing feature. The problem occurs for shapes crossing the allsky projections. It is tricky to spot because it depends on the projection. Usually what I do is:
* for every allsky projections except HPX and COD, I do not draw polygon where there is at least 3 consecutive vertices that are not defined in the same wise as the others (either every triplets are ccw or there are all in cw order but not a mix between ccw and cw order).
* for HPX I do not draw polygons that have at least 2 vertices in different collignon zones. A collignon zone is the top/bottom triangle you see in the hpx plane. There are 8 of them (4 on top and 4 on the bottom)
image
* For COD, I do not have the algorithm. Maybe I will hide that projection because it is very used and it leads to several problems.

I can benefit that PR to commit that

**Comment by szpetny** [comment]
I could try to fix it if it was helpful.

**Comment by bmatthieu3** [comment]
Yes if you want you can but it is just that I have some code on that lying somewhere and therefore it should not take me to much time to add it.
Is it possible that you add your screenshot as a new example ? Apart from that, how do you determine the coo of healpix cells vertices ? Did you use a specific js HEALPix library ?

**Comment by szpetny** [comment]
Ok then I will just add the example 🦖

> Did you use a specific js HEALPix library ?

Nope, I used HealpixCache from the old Aladin, as you told me not to x]
But perhaps I will look for sth at some point...

**Comment by bmatthieu3** [comment]
For non-sin/non-hpx projections I checked again the code I made for handling it in rust when drawing the moc cells and indeed it was more based on the length of the lines in the clipping projection space. Your code was good, the problem I think is just that sometimes the beginning of the draw of a polygon does not begin at index 0 but later. And so for these cases, it does not move first and do the beginpath, it keeps the path of the previous polygon and continue drawing it!
This is not a very good either, I do not like this index trick I made. Maybe I will change it later.

I also added the code for hpx projections.

**Comment by szpetny** [comment]
> a polygon does not begin at index 0 but later. And so for these cases, it does not move first and do the beginpath, it keeps the path of the previous polygon and continue drawing it!

But the examples I added work fine now. So it depends on data? And so it cannot be merged?

**Comment by bmatthieu3** [comment]
I merge it, if I have time I may factorize it later but it not very important

**Comment by szpetny** [comment]
great, thanks! :)

**Pull request merged**
