### PR TITLE
add codemeta and its validatior action

### PR DESCRIPTION
**Pull request by ManonMarchand**
This PR implements : 
- add a codemeta file according to [the codemeta shema](https://codemeta.github.io/)
- add a github action that checks its validity with the criterias of the OSSR 

Still to be done before merging : 
- [x] check I didn't write wrong stuff
- [ ] add zenodo doi in `identifier` field
- [x] the validator is not really happy with the "v3" version number cause it's not compliant with their recommended standard ([semantic versionning](https://semver.org/)). Do we have something like "3.0.0" here ? Can be ignored, it's just a warning. 
- [ ] other optional warnings raised are : 

```
CodemetaRecommendedWarning: Missing 5 recommended keys: ['memoryRequirements' 'processorRequirements' 'releaseNotes' 'storageRequirements' 'copyrightHolder']
```
edit : added the release notes

### CODE REVIEW

**Comment by bmatthieu3** [comment]
That's all good for the metadata for me, @tboch is it ok for you ?

**Comment by tboch** [comment]
Looks good indeed.
Version can be updated to 3.0.0, as this should be the version in https://github.com/cds-astro/aladin-lite/blob/1d1f277e0f498d9179cbb3bf56de7e1163792fb9/src/js/Aladin.js#L446 (cc @bmatthieu3 )

**Comment by ManonMarchand** [comment]
looks ready to me then, I made the change to version 3.0.0

**Comment by tboch** [comment]
OK, what's the next step now?

**Comment by ManonMarchand** [comment]
(I don't have the rights to merge this)
I'll switch to the rocket chat for the next steps.

**Pull request merged**
